
server:
  port: 9998
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  user:
    name: admin
    password: 123456
management:
  security:
    enabled: false
spring:
  application:
    name: admin-test
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        location: monitor-service
logging:
  file: "logs/admin-service-pro.log"