# remote git
server:
  port: 8769
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bomeixiaoxue/springcloud
          username: 2267919161@qq.com
          password:  # 公开的项目可以不用密码
      label: master

management:
  security:
    enabled: false

# ---native
#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#  application:
#    name: config-server

#
## port
#server:
#  port: 8769

#management:
#  security:
#    enabled: false



